### gpt-4-code-interpreter 调用
POST http://127.0.0.1:8080/api/conversion
Content-Type: application/json

{
  "action": "next",
  "messages": [
    {
      "role": "user",
      "content": "请帮我画一下张好看的gif图片，关于旋转的立方体。"
    }
  ],
  "stream": false
}
